spring:
  jpa:
    show-sql: true

  properties:
    hibernate:
      format_sql: true


  application:
    name: service1
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo-service1
    topic:
      metrics: t1_demo_metrics
      data-source-error: t1_demo_data_source_error
      time-limit-exceed: t1_demo_time_limit_exceed
      transaction: t1_demo_transactions
      account: t1_demo_accounts
      transaction_accept: t1_demo_transaction_accept
      transaction_result: t1_demo_transaction_result

management:
  endpoints:
    web.exposure.include: health, prometheus, metrics
  endpoint:
    health:
      show-details: always